apiVersion: batch/v1
kind: Job
metadata:
        name: job
spec:
        template:
                spec:
                        restartPolicy: OnFailure
                        containers:
                                - image: worker
                                  name: worker
                                  env:
                                          - name: PORT
                                            value: "50051"
                                          - name: ECHO
                                            value: "foo"
                                  ports:
                                          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
        name: job
        labels:
                app: job
spec:
        selector:
                app: job
        ports:
                - port: 50051
                  targetPort: 50051
                  protocol: TCP
                  name: grpc
