apiVersion: apps/v1
kind: Deployment
metadata:
        name: controller
spec:
        selector:
                matchLabels:
                        app: controller
        template:
                metadata:
                        labels:
                                app: controller
                spec:
                        containers:
                                - name: controller
                                  image: controller
                                  ports:
                                          - containerPort: 9090
                                  env:
                                          - name: PORT
                                            value: "9090"
                                          - name: "N"
                                            value: "10"
                                          - name: JOB_CHANNEL
                                            value: "worker.default.svc.cluster.local:50051"
---
apiVersion: v1
kind: Service
metadata:
        name: controller
        labels:
                app: controller
spec:
        selector:
                app: controller
        ports:
                - port: 80
                  targetPort: 9090

